### ISSUE TITLE
Include my workflow

### ISSUE THREAD

**Issue by xiaozhuai** [learn-anything/alfred-workflows#28]
Please include this
[https://github.com/xiaozhuai/alfred-adb](https://github.com/xiaozhuai/alfred-adb)

**Comment by nikivdev** [comment]
I read readme and find it confusing still what the workflow does. Also if you want it added, make PR although I question the utility of the workflow.

**Comment by xiaozhuai** [comment]
@nikitavoloboev 
Thanks!
This workflow can capture & record screen for android device via adb tool.
You can click the preview image to see the video.
